### ISSUE TITLE
Wrong Link in Active Record Validations Lesson

### ISSUE THREAD

**Issue by karen-olson** [learn-co-curriculum/phase-4-quiz-validations#1]
### Canvas Link

https://learning.flatironschool.com/courses/4324/pages/active-record-validations

### Concern

In the Lifecycle Timing section, it says that database activity triggers validation, and links to [Section 4 of this page](https://guides.rubyonrails.org/active_record_callbacks.html#running-callbacks) with a list of methods that trigger validation. This section lists methods that trigger callbacks, not validation. In the Validations quiz, there is a link to [methods that trigger validation](https://guides.rubyonrails.org/active_record_validations.html#when-does-validation-happen-questionmark), which is different from what was listed in the lesson. I came away from the lesson thinking that any method that triggered database activity (including destroy methods, toggle, and touch) would trigger validations as well, but it wasn't until I completed the quiz that I realized those methods trigger callbacks, not validations. 

### Suggested Changes

It would be great to clarify that the only methods that trigger validations are the methods listed in section 1.2 of the [validations page](https://guides.rubyonrails.org/active_record_validations.html#when-does-validation-happen-questionmark), and to remove the information about callbacks because it's not relevant to the current topic. 

Thanks!

**Comment by lizbur10** [comment]
Hi @karen-olson ! Thanks for bringing this to our attention! The link in the lesson has been updated. Please note that you may not see the change on your lesson page in Canvas, but it will be present for students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙
